import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex min-h-screen flex-col">
          <header className="bg-blue-600 p-4 text-white">
            <div className="container mx-auto">
              <div className="flex items-center justify-between">
                <h1 className="text-xl font-semibold">My News App</h1>
                <nav>
                  <ul className="flex space-x-4">
                    <li>
                      <Link href="/login" className="hover:underline">
                        Login
                      </Link>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
          </header>
          <main className="container mx-auto flex-grow p-4">
            <h2 className="mb-4 text-2xl font-bold">Welcome to My News App</h2>
            <p>
              {
                "This is a simple news application built with React and Tailwind CSS. Click on the 'Login' link in the header to log in."
              }
            </p>
          </main>
          <footer className="bg-gray-200 p-4 text-gray-800">
            <div className="container mx-auto text-center">
              <p>&copy; 2023 My News App. All rights reserved.</p>
            </div>
          </footer>
        </div>
      </main>
    </>
  );
};

export default Home;
